name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Bundle
        run: bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: rails_github_actions
          PGPASSWORD: postgres
        run: rake db:create db:migrate db:test:prepare

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: rails_github_actions
          PGPASSWORD: postgres
          RAILS_ENV: test
          jwt_string: foo
          jwt_encryption_algorithm: HS256
          client_id: id
        run: rspec

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov/lcov.info"
